# v0.2

blueprint:
  name: Défis Hilo – Automatisation simplifiée (Ari Version)
  description: Gestion des défis Hilo avec filtrage AM/PM et remise à la normale en fin de défi
  domain: automation

  input:
    default_challenge_entity:
      name: Entité du défi Hilo (capteur d'état)
      selector:
        entity:
          domain: sensor

    challenge_thermostats:
      name: Thermostats à gérer (au moins 1 requis)
      selector:
        entity:
          domain: climate
          multiple: true
      required: true

    water_heater_switch:
      name: Interrupteur Chauffe-eau (optionnel)
      default: []
      selector:
        entity:
          domain: switch
          multiple: true

    other_devices_switch:
      name: Autres appareils à couper (optionnel)
      default: []
      selector:
        entity:
          domain: switch
          multiple: true

    # Températures
    normal_temp:
      name: Température normale
      default: 19
      selector:
        number:
          step: 0.5
          min: 5
          max: 30
          unit_of_measurement: °C

    appreciation_temp:
      name: Température pendant appréciation
      description: Si appréciation est configurée dans Hilo
      default: 21
      selector:
        number:
          step: 0.5
          min: 5
          max: 30
          unit_of_measurement: °C

    pre_heat_temp:
      name: Température pré-chauffage
      description: 2h avant Réduction/Défi
      default: 21
      selector:
        number:
          step: 0.5
          min: 5
          max: 30
          unit_of_measurement: °C

    challenge_temp:
      name: Température pendant Réduction/Défi
      default: 17
      selector:
        number:
          step: 0.5
          min: 5
          max: 30
          unit_of_measurement: °C

    # Flags
    do_appreciation:
      name: Activer Appreciation
      default: true
      selector:
        boolean: {}

    do_pre_heat:
      name: Activer Pré-chauffage
      default: true
      selector:
        boolean: {}

    bool_shut_thermostat:
      name: Fermer thermostats pendant réduction
      description: Éteint les thermostats au lieu de régler une température
      default: false
      selector:
        boolean: {}

    challenge_am:
      name: Défis AM
      default: true
      selector:
        boolean: {}

    challenge_pm:
      name: Défis PM
      default: true
      selector:
        boolean: {}

trigger:
  - platform: state
    entity_id: !input default_challenge_entity
    to:
      - pre_heat
      - reduction
      - appreciation
      - recovery

variables:
  # Entité et état
  challenge_entity: !input default_challenge_entity
  challenge_state: "{{ states(challenge_entity) | lower }}"

  # Flags
  challenge_am_flag: !input challenge_am
  challenge_pm_flag: !input challenge_pm
  do_appreciation_flag: !input do_appreciation
  do_pre_heat_flag: !input do_pre_heat
  shut_thermostat_flag: !input bool_shut_thermostat

  # Cibles
  challenge_thermostats_var: !input challenge_thermostats
  water_heater_switch_var: !input water_heater_switch
  other_devices_switch_var: !input other_devices_switch

  # Comptages sécurisés
  water_heater_count: "{{ (water_heater_switch_var | default([], true)) | count }}"
  other_devices_count: "{{ (other_devices_switch_var | default([], true)) | count }}"

  # Données Hilo (sécurisées)
  hilo_events: >
    {{ state_attr(challenge_entity, 'next_events') | default([], true) }}

  hilo_next_period: >
    {{ hilo_events[0].period
       if hilo_events | length > 0 and 'period' in hilo_events[0]
       else 'none' }}

  is_am_window: "{{ hilo_next_period == 'am' }}"
  is_pm_window: "{{ hilo_next_period == 'pm' }}"

  # Autorisation AM / PM
  window_ok: >
    {{ (challenge_am_flag and is_am_window)
       or (challenge_pm_flag and is_pm_window) }}

action:
  - choose:

      # ---------- Pré-chauffage ----------
      - conditions:
          - condition: template
            value_template: >
              {{ challenge_state == 'pre_heat'
                 and do_pre_heat_flag
                 and window_ok }}
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input challenge_thermostats
            data:
              temperature: !input pre_heat_temp

      # ---------- Réduction ----------
      - conditions:
          - condition: template
            value_template: >
              {{ challenge_state == 'reduction'
                 and window_ok }}
        sequence:
          - if:
              - condition: template
                value_template: "{{ shut_thermostat_flag }}"
            then:
              - service: climate.turn_off
                target:
                  entity_id: !input challenge_thermostats
            else:
              - service: climate.set_temperature
                target:
                  entity_id: !input challenge_thermostats
                data:
                  temperature: !input challenge_temp

          - if:
              - condition: template
                value_template: "{{ water_heater_count > 0 }}"
            then:
              - service: switch.turn_off
                target:
                  entity_id: !input water_heater_switch

          - if:
              - condition: template
                value_template: "{{ other_devices_count > 0 }}"
            then:
              - service: switch.turn_off
                target:
                  entity_id: !input other_devices_switch

      # ---------- Appréciation ----------
      - conditions:
          - condition: template
            value_template: >
              {{ challenge_state == 'appreciation'
                 and do_appreciation_flag
                 and window_ok }}
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input challenge_thermostats
            data:
              temperature: !input appreciation_temp

      # ---------- Récupération  ----------
      - conditions:
          - condition: template
            value_template: "{{ challenge_state == 'recovery' and window_ok }}"
        sequence:
          - service: climate.turn_on
            target:
              entity_id: !input challenge_thermostats

          - service: climate.set_temperature
            target:
              entity_id: !input challenge_thermostats
            data:
              temperature: !input normal_temp

          - if:
              - condition: template
                value_template: "{{ water_heater_count > 0 }}"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input water_heater_switch

          - if:
              - condition: template
                value_template: "{{ other_devices_count > 0 }}"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input other_devices_switch

mode: restart
