# v0.2

blueprint:
  name: Défis Hilo – Automatisation simplifiée (Ari Version)
  description: Gestion des défis Hilo avec filtrage AM/PM et remise à la normale en fin de défi
  domain: automation

  input:
    default_challenge_entity:
      name: Entité du défi Hilo (capteur d'état)
      selector:
        entity:
          domain: sensor

    challenge_thermostats:
      name: Thermostats à gérer (au moins 1 requis)
      selector:
        entity:
          domain: climate
          multiple: true
    #-  required: true
    # Rend la sélection obligatoire (supprime les listes vides)
    
    switch_devices:
      name: Interrupteur (optionnel)
      description: Permet de à désactiver les équipements types SWITCH durant les défis et les phases d'appréciation de référence (Chauffe-Eau ou autres)
      default: []
      selector:
        entity:
          domain: switch
          multiple: true

    automations_interrupts:
      name: Automates (optionnel)
      description: Permet de à désactiver des automates durant les défis
      default: []
      selector:
        entity:
          domain: automation
          multiple: true

    # Températures
    normal_temp:
      name: Température normale
      description: Température pour les moments sans défis (ni référence, ni appréciation)
      default: 19
      selector:
        number:
          step: 0.5
          min: 5
          max: 30
          unit_of_measurement: °C

    appreciation_temp:
      name: Température pendant appréciation
      description: Si appréciation est configurée dans Hilo
      default: 21
      selector:
        number:
          step: 0.5
          min: 5
          max: 30
          unit_of_measurement: °C

    pre_heat_temp:
      name: Température pré-chauffage
      description: Pré-chauffer avant la réduction (équivalent au pré-chauffage de l'appli Hilo)
      default: 21
      selector:
        number:
          step: 0.5
          min: 5
          max: 30
          unit_of_measurement: °C

    challenge_temp:
      name: Température pendant Réduction/Défi
      default: 17
      selector:
        number:
          step: 0.5
          min: 5
          max: 30
          unit_of_measurement: °C

    # Flags
    do_appreciation:
      name: Activer Appreciation
      default: true
      selector:
        boolean: {}

    do_pre_heat:
      name: Activer Pré-chauffage
      description: Pré-chauffer avant la réduction (équivalent au pré-chauffage de l'appli Hilo)
      default: true
      selector:
        boolean: {}

    bool_shut_thermostat:
      name: Fermer thermostats pendant réduction
      description: Éteint les thermostats au lieu de régler une température
      default: false
      selector:
        boolean: {}

    challenge_am:
      name: Défis AM
      description: Va participer aux défis AM (incluant la référence)
      default: true
      selector:
        boolean: {}

    challenge_pm:
      name: Défis PM
      description: Va participer aux défis PM (incluant la référence)
      default: true
      selector:
        boolean: {}

trigger:
  - platform: state
    entity_id: !input default_challenge_entity
    to:
      - pre_heat
      - reduction
      - appreciation
      - recovery

variables:
  # Entité et état
  challenge_entity: !input default_challenge_entity
  challenge_state: "{{ states(challenge_entity) | lower }}"

  # Flags
  challenge_am_flag: !input challenge_am
  challenge_pm_flag: !input challenge_pm
  do_appreciation_flag: !input do_appreciation
  do_pre_heat_flag: !input do_pre_heat
  shut_thermostat_flag: !input bool_shut_thermostat

  # Cibles
  switch_devices_var: !input switch_devices
  automations_interrupts_var: !input automations_interrupts

  # Comptages sécurisés
  switch_devices_count: "{{ (switch_devices_var | default([], true)) | count }}"
  automations_interrupts_count: "{{ (automations_interrupts_var | default([], true)) | count }}"

  hilo_next_period: "{{ state_attr('sensor.defi_hilo', 'next_events')[0].period }}"

  is_am_window: "{{ hilo_next_period == 'am' }}"
  is_pm_window: "{{ hilo_next_period == 'pm' }}"

  # Autorisation AM / PM
  window_ok: >
    {{ (challenge_am_flag and is_am_window)
       or (challenge_pm_flag and is_pm_window) }}

action:
  - choose:

      # ---------- Pré-chauffage ----------
      - conditions:
          - condition: template
            value_template: >
              {{ challenge_state == 'pre_heat'
                 and do_pre_heat_flag
                 and window_ok }}
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input challenge_thermostats
            data:
              temperature: !input pre_heat_temp

      # ---------- Réduction ----------
      - conditions:
          - condition: template
            value_template: >
              {{ challenge_state == 'reduction'
                 and window_ok }}
        sequence:
          - if:
              - condition: template
                value_template: "{{ shut_thermostat_flag }}"
            then:
              - service: climate.turn_off
                target:
                  entity_id: !input challenge_thermostats
            else:
              - service: climate.set_temperature
                target:
                  entity_id: !input challenge_thermostats
                data:
                  temperature: !input challenge_temp

          - if:
              - condition: template
                value_template: "{{ switch_devices_count > 0 }}"
            then:
              - service: switch.turn_off
                target:
                  entity_id: !input switch_devices

          - if:
              - condition: template
                value_template: "{{ automations_interrupts_count > 0 }}"
            then:
              - service: automation.turn_off
                target:
                  entity_id: !input automations_interrupts


      # ---------- Appréciation ----------
      - conditions:
          - condition: template
            value_template: >
              {{ challenge_state == 'appreciation'
                 and do_appreciation_flag
                 and window_ok }}
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input challenge_thermostats
            data:
              temperature: !input appreciation_temp

      # ---------- Récupération  ----------
      - conditions:
          - condition: template
            value_template: "{{ challenge_state == 'recovery' and window_ok }}"
        sequence:
          - service: climate.turn_on
            target:
              entity_id: !input challenge_thermostats

          - service: climate.set_temperature
            target:
              entity_id: !input challenge_thermostats
            data:
              temperature: !input normal_temp

          - if:
              - condition: template
                value_template: "{{ switch_devices_count > 0 }}"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input switch_devices

          - if:
              - condition: template
                value_template: "{{ automations_interrupts_count > 0 }}"
            then:
              - service: automation.turn_on
                target:
                  entity_id: !input automations_interrupts

mode: restart
