blueprint:
  name: Défis Hilo – Automatisation simplifiée (Ari Version)
  description: Gestion des défis Hilo avec filtrage AM/PM et remise à la normale en fin de défi
  domain: automation

  input:
    default_challenge_entity:
      name: Entité du défi Hilo (capteur d'état)
      selector:
        entity:
          domain: sensor

    challenge_thermostats:
      name: Thermostats à gérer (au moins 1 requis)
      selector:
        entity:
          domain: climate
          multiple: true
    #-  required: true
    # Rend la sélection obligatoire (supprime les listes vides)

    water_heater_switch:
      name: Interrupteur Chauffe-eau (optionnel)
      default: []
      selector:
        entity:
          domain: switch
          multiple: true

    other_devices_switch:
      name: Autres appareils à couper (optionnel)
      default: []
      selector:
        entity:
          domain: switch
          multiple: true

    # Températures
    normal_temp:
      name: Température normale
      default: 19
      selector:
        number:
          step: 0.5
          min: 5
          max: 30
          unit_of_measurement: °C

    appreciation_temp:
      name: Température pendant appréciation
      description: 1 a 3AM et 12 a 2PM si appréciation est configuré à 2h dans l'intégration Hilo
      default: 21
      selector:
        number:
          step: 0.5
          min: 5
          max: 30
          unit_of_measurement: °C

    pre_heat_temp:
      name: Température pré-chauffage
      description: 2h avant Réduction/Défi
      default: 21
      selector:
        number:
          step: 0.5
          min: 5
          max: 30
          unit_of_measurement: °C

    challenge_temp:
      name: Température pendant Réduction/Défi
      default: 17
      selector:
        number:
          step: 0.5
          min: 5
          max: 30
          unit_of_measurement: °C

    # Flags
    do_appreciation:
      name: Activer Appreciation
      default: true
      selector:
        boolean: {}

    do_pre_heat:
      name: Activer Pré-chauffage
      default: true
      selector:
        boolean: {}

    bool_shut_thermostat:
      name: Fermer thermostats pendant réduction (au lieu de régler une température)
      description: Désactive les thermostats durant la phase de réducition au lieu de réduire la température (True)
      default: false
      selector:
        boolean: {}

    challenge_am:
      name: Défis AM
      default: true
      selector:
        boolean: {}

    challenge_pm:
      name: Défis PM
      default: true
      selector:
        boolean: {}

trigger:
  - platform: state
    entity_id: !input default_challenge_entity
  - platform: time
    at: "06:45:00"
  - platform: time
    at: "19:00:00"

variables:
  # Entité & état du défi
  challenge_entity: !input default_challenge_entity
  challenge_state: "{{ states(challenge_entity) | lower }}"

  # Sélection utilisateur (flags)
  challenge_am_flag: !input challenge_am
  challenge_pm_flag: !input challenge_pm
  do_appreciation_flag: !input do_appreciation
  do_pre_heat_flag: !input do_pre_heat
  shut_thermostat_flag: !input bool_shut_thermostat

  # Cibles (affectations directes des inputs — pas dans un template)
  challenge_thermostats_var: !input challenge_thermostats
  water_heater_switch_var: !input water_heater_switch
  other_devices_switch_var: !input other_devices_switch

  # Comptages sécurisés pour interrupteurs optionnels
  water_heater_count: "{{ (water_heater_switch_var | default([], true)) | count }}"
  other_devices_count: "{{ (other_devices_switch_var | default([], true)) | count }}"

  # Heure courante (locale HA)
  hour: "{{ now().hour }}"

  # Fenêtres AM/PM selon l'état courant
  # AM: appréciation 01–03, pré-chauffage 04–06, réduction 06–10, récupération 10–11
  is_am_window: >
    {% if challenge_state == 'appreciation' %}
      {{ (hour >= 1) and (hour < 4) }}
    {% elif challenge_state == 'pre_heat' %}
      {{ (hour >= 4) and (hour < 6) }}
    {% elif challenge_state == 'reduction' %}
      {{ (hour >= 6) and (hour < 10) }}
    {% elif challenge_state == 'recovery' %}
      {{ (hour >= 10) and (hour < 11) }}
    {% else %}
      false
    {% endif %}

  # PM: appréciation 11–14, pré-chauffage 14–16, réduction 16–20, récupération 20–21
  is_pm_window: >
    {% if challenge_state == 'appreciation' %}
      {{ (hour >= 11) and (hour < 14) }}
    {% elif challenge_state == 'pre_heat' %}
      {{ (hour >= 14) and (hour < 16) }}
    {% elif challenge_state == 'reduction' %}
      {{ (hour >= 16) and (hour < 20) }}
    {% elif challenge_state == 'recovery' %}
      {{ (hour >= 20) and (hour < 21) }}
    {% else %}
      false
    {% endif %}

  # Autorisation en fonction du choix AM/PM et de la fenêtre active
  window_ok: >
    {{ (challenge_am_flag and is_am_window) or (challenge_pm_flag and is_pm_window) }}

action:
  - choose:
      # ---------- Pré-chauffage ----------
      - conditions:
          - condition: template
            value_template: "{{ challenge_state == 'pre_heat' and do_pre_heat_flag and window_ok }}"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input challenge_thermostats
            data:
              temperature: !input pre_heat_temp

      # ---------- Réduction ----------
      - conditions:
          - condition: template
            value_template: "{{ challenge_state == 'reduction' and window_ok }}"
        sequence:
          # Thermostats: soit Off, soit Température de réduction
          - if:
              - condition: template
                value_template: "{{ shut_thermostat_flag }}"
            then:
              - service: climate.turn_off
                target:
                  entity_id: !input challenge_thermostats
            else:
              - service: climate.set_temperature
                target:
                  entity_id: !input challenge_thermostats
                data:
                  temperature: !input challenge_temp

          # Couper le chauffe-eau si une cible est fournie
          - if:
              - condition: template
                value_template: "{{ water_heater_count > 0 }}"
            then:
              - service: switch.turn_off
                target:
                  entity_id: !input water_heater_switch

          # Couper les autres appareils si une cible est fournie
          - if:
              - condition: template
                value_template: "{{ other_devices_count > 0 }}"
            then:
              - service: switch.turn_off
                target:
                  entity_id: !input other_devices_switch

      # ---------- Appréciation ----------
      - conditions:
          - condition: template
            value_template: "{{ challenge_state == 'appreciation' and do_appreciation_flag and window_ok }}"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input challenge_thermostats
            data:
              temperature: !input appreciation_temp

      # ---------- Récupération : remise à la normale ----------
      - conditions:
          - condition: template
            value_template: "{{ challenge_state == 'recovery' and window_ok }}"
        sequence:
          - service: climate.turn_on
            target:
              entity_id: !input challenge_thermostats
          - service: climate.set_temperature
            target:
              entity_id: !input challenge_thermostats
            data:
              temperature: !input normal_temp

          # Rallumer le chauffe-eau si une cible est fournie
          - if:
              - condition: template
                value_template: "{{ water_heater_count > 0 }}"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input water_heater_switch

          # Rallumer les autres appareils si une cible est fournie
          - if:
              - condition: template
                value_template: "{{ other_devices_count > 0 }}"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input other_devices_switch
mode: restart
